idf_component_register(
    SRCS
        "logOS.c"
        "logos_start.c"
        "components/shell/shell.c"
        "components/user/user_syscall.c"
        "components/kernel/block.c"
        "components/kernel/console.c"
        "components/kernel/device.c"
        "components/kernel/dir.c"
        "components/kernel/file.c"
        "components/kernel/fs_alloc.c"
        "components/kernel/fs.c"
        "components/kernel/inode.c"
        "components/kernel/kernel_time.c"
        "components/kernel/logos_partition.c"
        "components/kernel/trap.c"
        "components/kernel/trap.S"
        "components/kernel/esp32c3/syscall.c"
        "components/kernel/esp32c3/sys_console.c"
        #"components/kernel/logos_string.c"
        #"components/kernel/logos_string.h"
    INCLUDE_DIRS
        "."
        "components/kernel"
        "components/kernel/esp32c3"
        "components/shell"
        "components/user"
)
