idf_component_register(SRCS 
"logosTest2.c" 
"kernel/fs.h" 
"kernel/types.h" 
"kernel/fs_types.h" 
"kernel/string.h" 
"kernel/console.h" 
"kernel/block.h" 
"kernel/inode.h" 
"kernel/dir.h" 
"kernel/file.h" 
"kernel/device.h" 
"kernel/elf.h" 
"kernel/loader.h" 
"kernel/trap.h" 
"kernel/syscall.h" 
"kernel/process.h" 
"kernel/esp32_block.c" 
"kernel/dir.c" 
"kernel/fs.c" 
"kernel/loader.c" 
"kernel/process.c" 
"kernel/syscall.c" 
"kernel/device.c" 
"kernel/file.c" 
"kernel/inode.c" 
"kernel/main.c" 
"kernel/crt0.S" 
"kernel/loader_asm.S" 
"kernel/trap.S" 
INCLUDE_DIRS ".")
 littlefs_create_partition_image(storage ../flash_data FLASH_IN_PROJECT)
